<?php
declare(strict_types=1);

require_once __DIR__ . '/../../src/Database/Database.php';
require_once __DIR__ . '/../../src/Auth/JWT.php';
require_once __DIR__ . '/../../src/Models/User.php';
require_once __DIR__ . '/../../src/Auth/AuthController.php';

use DTZ\Auth\AuthController;
use DTZ\Database\Database;

header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: Content-Type, Authorization');
header('Access-Control-Allow-Methods: POST, OPTIONS');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(204);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['error' => 'Nur POST erlaubt']);
    exit;
}

// Auth
$authHeader = $_SERVER['HTTP_AUTHORIZATION'] ?? '';
$token = '';
if (preg_match('/Bearer\s+(\S+)/', $authHeader, $matches)) {
    $token = $matches[1];
}

if (empty($token)) {
    http_response_code(401);
    echo json_encode(['error' => 'Nicht autorisiert']);
    exit;
}

$auth = new AuthController();
$user = $auth->me($token);

if (!$user) {
    http_response_code(401);
    echo json_encode(['error' => 'Token ungültig']);
    exit;
}

try {
    $db = Database::getInstance();
    
    // Check for existing incomplete test
    $existing = $db->selectOne(
        "SELECT id, current_module FROM modelltest_attempts 
         WHERE user_id = ? AND status = 'in_progress' 
         ORDER BY started_at DESC LIMIT 1",
        [$user['id']]
    );
    
    if ($existing) {
        http_response_code(409);
        echo json_encode([
            'error' => 'Bereits laufender Test',
            'attempt_id' => $existing['id'],
            'current_module' => $existing['current_module']
        ]);
        exit;
    }
    
    // ID will be auto-generated by SQLite
    
    $now = new DateTime();
    $startTime = $now->format('Y-m-d H:i:s');
    
    // Time limits per module (minutes)
    $timeLimits = [
        'hoeren' => 30,
        'lesen' => 45,
        'schreiben' => 30,
        'sprechen' => 15
    ];
    
    // Calculate end times
    $hoerenEnd = (clone $now)->modify("+{$timeLimits['hoeren']} minutes");
    $lesenEnd = (clone $hoerenEnd)->modify("+{$timeLimits['lesen']} minutes");
    $schreibenEnd = (clone $lesenEnd)->modify("+{$timeLimits['schreiben']} minutes");
    $sprechenEnd = (clone $schreibenEnd)->modify("+{$timeLimits['sprechen']} minutes");
    
    // Load questions for each module
    $questions = [
        'hoeren' => loadQuestions($db, 'hoeren', 20),
        'lesen' => loadQuestions($db, 'lesen', 30),
        'schreiben' => loadQuestions($db, 'schreiben', 2),
        'sprechen' => loadQuestions($db, 'sprechen', 3)
    ];
    
    // Calculate max possible score
    $maxScore = 0;
    foreach ($questions as $module => $qs) {
        foreach ($qs as $q) {
            $maxScore += ($q['points'] ?? 5);
        }
    }
    
    $attemptId = $db->insert('modelltest_attempts', [
        'user_id' => $user['id'],
        'started_at' => $startTime,
        'hoeren_end_time' => $hoerenEnd->format('Y-m-d H:i:s'),
        'lesen_end_time' => $lesenEnd->format('Y-m-d H:i:s'),
        'schreiben_end_time' => $schreibenEnd->format('Y-m-d H:i:s'),
        'sprechen_end_time' => $sprechenEnd->format('Y-m-d H:i:s'),
        'current_module' => 'hoeren',
        'status' => 'in_progress',
        'questions' => json_encode($questions),
        'max_possible_score' => $maxScore
    ]);
    
    echo json_encode([
        'success' => true,
        'attempt_id' => (int)$attemptId,
        'current_module' => 'hoeren',
        'time_limits' => [
            'hoeren' => $hoerenEnd->format('c'),
            'lesen' => $lesenEnd->format('c'),
            'schreiben' => $schreibenEnd->format('c'),
            'sprechen' => $sprechenEnd->format('c')
        ],
        'questions' => $questions['hoeren']
    ]);
    
} catch (Exception $e) {
    http_response_code(500);
    echo json_encode(['error' => 'Fehler beim Starten: ' . $e->getMessage()]);
}

function loadQuestions($db, $module, $limit) {
    // Get random questions for this module
    $questions = $db->select(
        "SELECT id, module, question_type, content, points, difficulty 
         FROM question_pools 
         WHERE module = ? AND is_active = TRUE 
         ORDER BY RANDOM() 
         LIMIT ?",
        [$module, $limit]
    );
    
    // Extract question data from content JSON
    $result = [];
    foreach ($questions as $q) {
        $content = json_decode($q['content'], true);
        $result[] = [
            'id' => $q['id'],
            'module' => $q['module'],
            'question_text' => $content['question'] ?? $content['text'] ?? '',
            'question_type' => $q['question_type'],
            'options' => $content['options'] ?? [],
            'points' => $q['points'] ?? 5,
            'difficulty' => $q['difficulty'] ?? 5
        ];
    }
    
    return $result;
}
